### ISSUE TITLE
Constant crashes when a lot of gh actions

### ISSUE THREAD

**Issue by juris** [Spendesk/github-actions-exporter#49]
With too many (20+) gh actions in place, exporter started to crash with the following error:
```
2022/08/08 12:03:47 authenticating with Github Token
2022/08/08 12:03:48 exporter listening on 0.0.0.0:9999
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x99451b]

goroutine 45 [running]:
github-actions-exporter/pkg/metrics.getFieldValue(0xc00002600d, 0x12, 0xc0001c8520, 0xc000253200, 0xc000253210, 0xc000253220, 0xc000253230, 0xc0001c8528, 0xc000253240, 0xc000253250, ...)
	/app/pkg/metrics/get_workflow_runs_from_github.go:32 +0x27b
github-actions-exporter/pkg/metrics.getRelevantFields(0xc00002600d, 0x12, 0xc0006b3180, 0x5, 0xb7c9e0, 0xc000234a40)
	/app/pkg/metrics/get_workflow_runs_from_github.go:46 +0x18e
github-actions-exporter/pkg/metrics.getWorkflowRunsFromGithub()
	/app/pkg/metrics/get_workflow_runs_from_github.go:72 +0xea
created by github-actions-exporter/pkg/metrics.InitMetrics
	/app/pkg/metrics/metrics.go:64 +0x52f
```

**Comment by tobifroe** [comment]
I'm running into the same error when scraping lots of repositories. Any update on this?

**Comment by papaslon** [comment]
It will be fixed in upcoming release. To be specific in this [commit](https://github.com/Spendesk/github-actions-exporter/commit/04e6c3119258727227306ce58c5b61d9674c247a). In the meantime you can use "image.tag: v1.9.0-beta1`

**Comment by moutonjeremy** [comment]
Hello,
Thank you @papaslon for the fix.
@juris @tobifroe it's merged in the main branch and release in v1.9.0
